name: Publish in GitHub Package Registry

on:  
  push:
    tags:
      - '*'

jobs:
  draft-new-release:
    uses: ./.github/workflows/draft-new-release.yml
    with:
      version: ${{ github.ref }}
