name: Publish in GitHub Package Registry
on:  
  push:
    tags:
      - 'v*.*.*'

jobs:
  draft-new-release:
    uses: ./.github/workflows/draft-new-release.yml
    with:
      ref_name: ${{ github.ref_name }}

