name: Gitflow
on: 
  # To create pull requests.
  push:
  # To merge pull requests if not possible during the push run. Remove if `auto-merge` is `false`.
  pull_request_review:
  check_run:
    types: [completed]

jobs:

  draft-new-release:
    uses: ./.github/workflows/draft-new-release.yml
    with:
      version: $(echo ${{ github.ref }} | sed "s/refs/tags/v//") 

